spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/ProductService
spring.datasource.username=root
spring.datasource.password=Babli@93
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
